import React from 'react';
import Link from 'next/link';
import Image from 'next/image';

interface LogoProps {
  variant?: 'full' | 'icon' | 'monochrome';
  className?: string;
  size?: number;
  href?: string;
}

export function Logo({ variant = 'full', className = '', size = 32, href = '/' }: LogoProps) {
  // Use the exact raster images generated by the AI
  const isIcon = variant === 'icon' || variant === 'monochrome';
  
  const width = isIcon ? size : size * 2.8;
  const height = size;
  
  const src = isIcon ? '/logo-icon.png' : '/logo-full.png';

  const content = (
    <div 
      className={`relative flex items-center justify-center shrink-0 ${variant !== 'icon' ? 'hover:opacity-90 transition-opacity' : ''} ${className}`}
      style={{ width, height }}
    >
      <Image 
        src={src} 
        alt="Collabo Logo" 
        fill
        className="object-contain"
        priority
      />
    </div>
  );

  if (href) {
    return <Link href={href} className="inline-block">{content}</Link>;
  }

  return content;
}
